bundler_args: "--without debug"
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
env:
  - "CI_ORM=active_record CI_DB_ADAPTER=sqlite3"
  - "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
  - "CI_ORM=active_record CI_DB_ADAPTER=mysql"
  - "CI_ORM=mongoid"
language: ruby
matrix:
  exclude:
    - rvm: jruby-19mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
    - rvm: jruby-19mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql"
    - rvm: rbx-19mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
    - rvm: rbx-19mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql"
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
notifications:
  irc: "irc.freenode.org#railsadmin"
script: spec/ci.sh
