bundler_args: "--without development"
rvm:
  - jruby-19mode
  - 1.9.3
  - 2.0.0
env:
  - "CI_ORM=mongoid"
  - "CI_ORM=active_record CI_DB_ADAPTER=sqlite3"
  - "CI_ORM=active_record CI_DB_ADAPTER=mysql2"
  - "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
language: ruby
matrix:
  exclude:
    - rvm: jruby-19mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql2"
    - rvm: jruby-19mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
    - rvm: 1.9.3
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql2"
    - rvm: 1.9.3
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
notifications:
  irc: "irc.freenode.org#railsadmin"
before_script:
  - cd spec/dummy_app
  - bundle install
  - bundle exec rake rails_admin:prepare_ci_env
  - bundle exec rake db:create db:migrate
  - cd ../../
services:
  - mongodb
