language: ruby

before_install:
  # https://github.com/danmayer/coverband/issues/162#issuecomment-452173268
  - rm /home/travis/.rvm/gems/*/specifications/bundler-2.*.gemspec || true
  - gem install bundler -v '< 2'
  - ruby -e "exit RUBY_VERSION >= '2.6'" && gem update --system || true

before_script:
  - cd spec/dummy_app
  - bundle exec rake rails_admin:prepare_ci_env db:create db:migrate
  - cd ../../

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

cache: bundler

env:
  matrix:
    - CI_ORM=mongoid
    - CI_ORM=active_record CI_DB_ADAPTER=sqlite3
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

rvm:
  - 2.6.3

gemfile:
  - gemfiles/rails_6.0.gemfile

addons:
  postgresql: "9.4"

services:
  - mongodb

dist: trusty

matrix:
  include:
    - rvm: 2.2.10
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.2.10
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.3.8
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.3.8
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.4.5
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.4.5
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.5.5
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.5.5
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.6.3
      env: CI_ORM=active_record CI_DB_ADAPTER=mysql2
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.6.3
      env: CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: ruby-head
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: ruby-head
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: jruby-9.2.7.0
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: jruby-9.2.7.0
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: jruby-head
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
  exclude:
    - rvm: 2.6.3
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_6.0.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true

notifications:
  irc: irc.freenode.org#railsadmin
