bundler_args: "--without debug"
script: spec/ci.sh
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
env:
  - "CI_ORM=active_record CI_DB_ADAPTER=sqlite3"
  - "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
  - "CI_ORM=active_record CI_DB_ADAPTER=mysql"
  - "CI_ORM=mongoid"
  - "CI_ORM=mongoid CI_ORM_VERSION=head"
gemfile:
  - Gemfile
  - Gemfile31
language: ruby
matrix:
  exclude:
    - rvm: 1.8.7
      env: "CI_ORM=active_record CI_DB_ADAPTER=sqlite3"
      gemfile: Gemfile
    - rvm: 1.8.7
      env: "CI_ORM=active_record CI_DB_ADAPTER=sqlite3"
      gemfile: Gemfile31
    - rvm: 1.8.7
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
      gemfile: Gemfile
    - rvm: 1.8.7
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
      gemfile: Gemfile31
    - rvm: 1.8.7
      gemfile: Gemfile31
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql"
    - rvm: 1.8.7
      gemfile: Gemfile
      env: "CI_ORM=mongoid CI_ORM_VERSION=head"
    - rvm: 1.8.7
      gemfile: Gemfile31
      env: "CI_ORM=mongoid"
    - rvm: 1.8.7
      gemfile: Gemfile31
      env: "CI_ORM=mongoid CI_ORM_VERSION=head"

    - rvm: jruby-18mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql"
      gemfile: Gemfile
    - rvm: jruby-18mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql"
      gemfile: Gemfile31
    - rvm: jruby-18mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
      gemfile: Gemfile
    - rvm: jruby-18mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
      gemfile: Gemfile31
    - rvm: jruby-18mode
      env: "CI_ORM=active_record CI_DB_ADAPTER=sqlite3"
      gemfile: Gemfile31
    - rvm: jruby-18mode
      gemfile: Gemfile
      env: "CI_ORM=mongoid CI_ORM_VERSION=head"
    - rvm: jruby-18mode
      gemfile: Gemfile31
      env: "CI_ORM=mongoid"
    - rvm: jruby-18mode
      gemfile: Gemfile31
      env: "CI_ORM=mongoid CI_ORM_VERSION=head"

    - rvm: 1.9.3
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql"
      gemfile: Gemfile
    - rvm: 1.9.3
      env: "CI_ORM=active_record CI_DB_ADAPTER=mysql"
      gemfile: Gemfile31
    - rvm: 1.9.3
      gemfile: Gemfile31
      env: "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
notifications:
  irc: "irc.freenode.org#railsadmin"
