language: ruby

before_install: gem install bundler

before_script:
  - cd spec/dummy_app
  - bundle exec rake rails_admin:prepare_ci_env db:create db:migrate
  - cd ../../

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

cache: bundler

env:
  matrix:
    - CI_ORM=mongoid
    - CI_ORM=active_record CI_DB_ADAPTER=sqlite3
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

rvm:
  - 2.3.7

gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

services:
  - mongodb

dist: trusty

sudo: false

matrix:
  include:
    - rvm: 2.1.10
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.1.10
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.2.10
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.2.10
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.3.7
      env: CI_ORM=active_record CI_DB_ADAPTER=mysql2
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.3.7
      env: CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.3.7
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/cancan.gemfile
    - rvm: 2.4.4
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.4.4
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.5.1
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.5.1
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: ruby-head
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: ruby-head
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: rbx-2.2.7
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: jruby-9.1.9.0
      env: CI_ORM=mongoid
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: jruby-9.1.9.0
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: jruby-head
      env: CI_ORM=active_record CI_DB_ADAPTER=sqlite3
      gemfile: gemfiles/rails_5.1.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2.2.7
    - rvm: jruby-head
  fast_finish: true

notifications:
  irc: irc.freenode.org#railsadmin
